development:
  dialect: postgres
  datasource: host=ec2-18-210-214-86.compute-1.amazonaws.com port=5432 user=ldazsqpgqbtdve password=a3d557ae77a893a93bdd1bd330be6a98ca656b067d35e830461623546f95eb55 dbname=d228g64knl6omk sslmode=require
  dir: migrations/postgres
  table: migrations